### ISSUE TITLE
[BUG] Pot jails have 640 /etc/resolv.conf and user Ruby commands fail on network resolution

### ISSUE THREAD

**Issue by bretton** [bsdpot/pot#293]
**Describe the bug**
A user running Ruby scripts cannot read `/etc/resolv.conf` and the Ruby process cannot perform network resolution.

@grembo asked me to tag him

**To Reproduce**

This crops up in the mastodon pot image, where Ruby scripts happen as the mastodon user. 

The following line tests domain resolution.
```
sudo su - mastodon
ruby -rresolv -e 'puts Resolv::DNS.new.getresource("_rubygems._tcp.rubygems.org", Resolv::DNS::Resource::IN::SRV).target' 
```

**Expected behavior**
There should be a result of `api.rubygems.org`

**Actual behavior**
```
ruby -rresolv -e 'puts Resolv::DNS.new.getresource("_rubygems._tcp.rubygems.org", Resolv::DNS::Resource::IN::SRV).target' 

/usr/local/lib/ruby/3.2/resolv.rb:961:in `initialize': Permission denied @ rb_sysopen - /etc/resolv.conf (Errno::EACCES)
    from /usr/local/lib/ruby/3.2/resolv.rb:961:in `open'
    from /usr/local/lib/ruby/3.2/resolv.rb:961:in `parse_resolv_conf'
    from /usr/local/lib/ruby/3.2/resolv.rb:990:in `default_config_hash'
    from /usr/local/lib/ruby/3.2/resolv.rb:1011:in `block in lazy_initialize'
    from /usr/local/lib/ruby/3.2/resolv.rb:1004:in `synchronize'
    from /usr/local/lib/ruby/3.2/resolv.rb:1004:in `lazy_initialize'
    from /usr/local/lib/ruby/3.2/resolv.rb:353:in `block in lazy_initialize'
    from /usr/local/lib/ruby/3.2/resolv.rb:351:in `synchronize'
    from /usr/local/lib/ruby/3.2/resolv.rb:351:in `lazy_initialize'
    from /usr/local/lib/ruby/3.2/resolv.rb:513:in `fetch_resource'
    from /usr/local/lib/ruby/3.2/resolv.rb:507:in `each_resource'
    from /usr/local/lib/ruby/3.2/resolv.rb:488:in `getresource'
    from -e:1:in `<main>' 
```

**System configuration - if possible**
```
/usr/local/etc/pot/pot.conf

POT_ZFS_ROOT=zroot/opt/pot
POT_FS_ROOT=/opt/pot
POT_CACHE=/var/cache/pot
POT_TMP=/tmp
POT_NETWORK=10.1.2.0/24
POT_NETMASK=255.255.255.0
POT_GATEWAY=10.1.2.1
POT_EXTIF=jailnet
POT_DNS_IP=10.1.2.2
```

** If network related **
```
potnet show -v

18:05:54 [ INFO] Insert network 10.1.2.0/24
18:05:54 [ INFO] Insert broadcast 10.1.2.0/24
18:05:54 [ INFO] Insert gateway 10.1.2.1
18:05:54 [ INFO] Insert dns 10.1.2.2
18:05:54 [ INFO] Insert pot 10.1.2.12
18:05:54 [ INFO] Insert pot 10.1.2.117
18:05:54 [ INFO] Insert pot 10.1.2.16
18:05:54 [ INFO] Insert pot 10.1.2.111
18:05:54 [ INFO] Insert pot 10.1.2.7
18:05:54 [ INFO] Insert pot 10.1.2.17
18:05:54 [ INFO] Insert pot 10.1.2.113
18:05:54 [ INFO] Insert pot 10.1.2.6
18:05:54 [ INFO] Insert pot 10.1.2.250
18:05:54 [ INFO] Insert pot 10.1.2.15
18:05:54 [ INFO] Insert pot 10.1.2.3
18:05:54 [ INFO] Insert pot 10.1.2.114
18:05:54 [ INFO] Insert pot 10.1.2.112
18:05:54 [ INFO] Insert pot 10.1.2.14
18:05:54 [ INFO] Insert pot 10.1.2.116
18:05:54 [ INFO] Insert pot 10.1.2.9
18:05:54 [ INFO] Insert pot 10.1.2.115
18:05:54 [ INFO] Insert pot 10.1.2.10
18:05:54 [ INFO] Insert pot 10.1.2.8
18:05:54 [ INFO] Insert pot 10.1.2.110
18:05:54 [ INFO] Insert pot 10.1.2.5
18:05:54 [ INFO] Insert pot 10.1.2.13
18:05:54 [ INFO] Insert pot 10.1.2.4
18:05:54 [ INFO] Insert pot 10.1.2.11
Network topology:
	network : 10.1.2.0/24
	min addr: 10.1.2.0
	max addr: 10.1.2.255

Addresses already taken:
	10.1.2.0	
	10.1.2.1	default gateway
	10.1.2.2	dns
	10.1.2.3	freebsd-potluck-amd64-14_0_0_0_22_base
	10.1.2.4	consul-amd64-14_0_2_13_1
	10.1.2.5	beast-of-argh-amd64-14_0_0_13_1
	10.1.2.6	nginx-nomad-alt-amd64-14_0_0_11_1
	10.1.2.7	nginx-s3-ssl-nomad-amd64-14_0_0_2_1
	10.1.2.8	nomad-server-amd64-14_0_3_14_1
	10.1.2.9	stdwebsite_c939369c_1d44863c-c1ed-8f15-a5ef-13a9f420d304
	10.1.2.10	publicwebsite_be1085e9_48caf303-96a9-e25a-6d52-c942a156602e
	10.1.2.11	miniofrontend_34b1acac_c45be6cc-f2cf-d3df-8e56-11e64376ad89
	10.1.2.12	traefik-consul-amd64-14_0_1_16_1
	10.1.2.13	haproxy-minio-amd64-14_0_0_0_3
	10.1.2.14	zincsearch-amd64-14_0_0_2_1
	10.1.2.15	redis-single-amd64-14_0_0_4_1
	10.1.2.16	postgres-single-amd64-14_0_0_4_1
	10.1.2.17	mastodon-s3-amd64-14_0_0_9_3
	10.1.2.110	consul-clone
	10.1.2.111	nomad-server-clone
	10.1.2.112	traefik-consul-clone
	10.1.2.113	haproxy-minio-clone
	10.1.2.114	zincsearch-clone
	10.1.2.115	redis-single-clone
	10.1.2.116	postgres-single-clone
	10.1.2.117	mastodon-s3-clone
	10.1.2.250	beast-clone
	10.1.2.255	

Debug information
PotSystemConfig {
    zfs_root: "zroot/opt/pot",
    fs_root: "/opt/pot",
    network: 10.1.2.0/24,
    netmask: 255.255.255.0,
    gateway: 10.1.2.1,
    ext_if: "jailnet",
    dns: Some(
        PotDnsConfig {
            pot_name: "dns",
            ip: 10.1.2.2,
        },
    ),
}
```

**Additional context**
Setting the permissions on `/etc/resolv.conf` to `644` makes the problem go away as the mastodon user can read `/etc/resolv.conf`.

I can update the mastodon pot image to set permissions manually in the cook file, but I'm not sure if this is a valid approach?

**Comment by bretton** [comment]
> how did you configure dns in your pot image?

I'm not specifically configuring it, so whatever the default is.  The host has 644 and then the pots have 640.

```
pot clone \
        -P "{{ pot_mastodon_pot_name }}" \
        -p "{{ pot_mastodon_clone_name }}" \
        -N public-bridge -i "{{ pot_mastodon_ip }}" \
        -S "{{ potnet_network_type }}"
```

I'll try experiment with setting it and update later.

**Comment by bretton** [comment]
with `-d inherit` 
```
pot exec -p traefik-consul-clone ls -al /etc/resolv.conf
-rw-r-----  1 root wheel 46 Apr  9 19:20 /etc/resolv.conf
```

**Comment by grembo** [comment]
@bretton I cannot reproduce the issue

I tried:

```
# pot import -p traefik-consul-amd64-14_0 -t 1.16.1 -U https://potluck.honeyguide.net/traefik-consul
# ls -al /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf: No such file or directory
# pot clone -P "traefik-consul-amd64-14_0_1_16_1" -p "traefik-clone" -N public-bridge -i "10.192.0.101" -S "ipv4"
# grep dns /opt/pot/jails/traefik-clone/conf/*
/opt/pot/jails/traefik-clone/conf/pot.conf:pot.dns=inherit
# ls -al /opt/pot/jails/traefik-clone/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-clone/m/etc/resolv.conf: No such file or directory
# ls -al /etc/resolv.conf
-rw-r--r--  1 root  wheel  51 Aug 16  2023 /etc/resolv.conf
# pot start traefik-clone
...
# ls -al /opt/pot/jails/traefik-clone/m/etc/resolv.conf
-rw-r--r--  1 root  wheel  51 Apr 12 09:31 /opt/pot/jails/traefik-clone/m/etc/resolv.conf
# pot exec -p traefik-clone ls -al /etc/resolv.conf
-rw-r--r--  1 root wheel 51 Apr 12 09:31 /etc/resolv.conf
```

Maybe you can verify this sequence at your end?

**Comment by bretton** [comment]
> Maybe you can verify this sequence at your end?

It's working fine in my local setup, and not working on two Hetzner hosts. I'm not specifically setting anything on resolv.conf. I'll try another host too. Maybe it's not pot but something in server setup.

local box, vms
```
# pot import -p traefik-consul-amd64-14_0 -t 1.16.1 -U https://potluck.honeyguide.net/traefik-consul
# ls -al /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf: No such file or directory
# pot clone -P "traefik-consul-amd64-14_0_1_16_1" -p "traefik-consul-clone" -N public-bridge -i "10.1.2.101" -S "ipv4"
# grep dns /opt/pot/jails/traefik-consul-clone/conf/*
/opt/pot/jails/traefik-consul-clone/conf/pot.conf:pot.dns=inherit
# ls -al /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf: No such file or directory
# ls -al /etc/resolv.conf
-rw-r--r--  1 root wheel 46 Apr 12 21:15 /etc/resolv.conf
# pot start traefik-clone ...
# ls -al /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf
-rw-r--r--  1 root  wheel  51 Apr 12 09:31 /opt/pot/jails/traefik-clone/m/etc/resolv.conf
# pot exec -p traefik-consul-clone ls -al /etc/resolv.conf
-rw-r--r--  1 root wheel 51 Apr 12 09:31 /etc/resolv.conf
```

Server 1 @ hetzner, server 2 is doing the same thing.
```
# pot import -p traefik-consul-amd64-14_0 -t 1.16.1 -U https://potluck.honeyguide.net/traefik-consul
# ls -al /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-consul-amd64-14_0_1_16_1/m/etc/resolv.conf: No such file or directory
# pot clone -P "traefik-consul-amd64-14_0_1_16_1" -p "traefik-consul-clone" -N public-bridge -i "10.1.2.112" -S "ipv4"
# grep dns /opt/pot/jails/traefik-consul-clone/conf/*
/opt/pot/jails/traefik-consul-clone/conf/pot.conf:pot.dns=inherit
# ls -al /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf
ls: /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf: No such file or directory
# ls -al /etc/resolv.conf
-rw-r--r--  1 root wheel 46 Apr 12 19:46 /etc/resolv.conf
# pot start traefik-clone ...
# ls -al /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf
-rw-r-----  1 root wheel 46 Apr 12 20:30 /opt/pot/jails/traefik-consul-clone/m/etc/resolv.conf
# pot exec -p traefik-consul-clone ls -al /etc/resolv.conf
-rw-r-----  1 root wheel 46 Apr 12 20:30 /etc/resolv.conf
```

**Comment by bretton** [comment]
Sory, not a pot issue, relates to umask configuration in /etc/login.conf from depenguin.me installer. 

If host was installed this way, setup can be reverted with:
```
sed -i '' -e 's/:umask=027:/:umask=022:/g' /etc/login.conf 
cap_mkdb /etc/login.conf
```
